### ISSUE TITLE
Filtering / sorting list of nested objects

### ISSUE THREAD

**Issue by MandrivaX** [Biarity/Sieve#100]
Hello, 

I started using Sieve library but I encountered some problems when working with lists.

    public class Car
    {
        [Sieve(CanFilter = true)]
        public int Id { get; set; }

        [Sieve(CanFilter = true)]
        public string Name { get; set; }

        [Sieve(CanFilter = true)]
        public List<Wheel> Wheels{ get; set; }
    }

    public class Wheel
    {
        [Sieve(CanFilter = true)]
        public int Id { get; set; }

        [Sieve(CanFilter = true)]
        public string Name { get; set; }
    }

How to use mapping to filter the wheels into Car object, or get cars with some conditions for wheels

Thx for help

**Comment by a-patel** [comment]
Please check below:
https://github.com/Biarity/Sieve#nested-objects

**Comment by MandrivaX** [comment]
@a-patel Thx for your replay 

it's work with simple object relation, i look for mapping with list of objects, if you have an example 

Thx

**Comment by MandrivaX** [comment]
I think ISieveCustomFilterMethods will help me :)

**Comment by marrrschine** [comment]
hey @MandrivaX, did you manage to filter properties of collection items?

**Comment by MandrivaX** [comment]
@marrrschine  Yes,  by implementing ISieveCustomFilterMethods, and dont forget to inject it into statrup.cs.

    `public class CustomSieveFilterMethods : ISieveCustomFilterMethods
    {
        /// <summary>
        /// Check if subnetworks in list o values
        /// </summary>
        /// <param name="source"></param>
        /// <param name="op"></param>
        /// <param name="values"></param>
        /// <returns></returns>
        public IQueryable<Vehicule> NetworksIn(IQueryable<Personne> source, string op, string[] values)
        {
            var result = source.Where(
              p => (p.Adresses != null && p.Adresses.Any(
                  b => b.Networks != null && b.Networks.Any(
                      n => n.SubNetworks != null && n.SubNetworks.Any(
                          s => s != null && !string.IsNullOrEmpty(s.Name) && (values.Contains(s.Name) || values.Contains(s.Code)))))
                  )
              );
            return result;
        }
}`

**Comment by marrrschine** [comment]
Cool, thank you very much!
