### ISSUE TITLE
Passing data to MapProperties of SieveProcessor

### ISSUE THREAD

**Issue by dagema1** [Biarity/Sieve#105]
is it possible to pass data to SieveProcessor's MapProperties method?

I wanted to pass a user id to the mapper like this...

`mapper.Property<Post>(p => p.Subscribers.Any(s => s.UserId == userId))`
`.CanFilter()`
`.HasName("isSubscribed");`

thanks.

**Comment by hasanmanzak** [comment]
No, this is not possible with the way how `SievePropertyMapper` works. Even if it was, logically, this is bogus. Say the development is done to support that kind of mapping. Think about it, when runtime hits that `.Property<>` line, `userId` is converted to an expression constant, it won't be a dynamic value. Or look it this way, where would the `userId` value is supplied to execute the expression `s => s.UserId == userId` if your intention was to use a variable?

This is textbook [Custom Filter Method](https://github.com/Biarity/Sieve#add-custom-sortfilter-methods) implementation, which would handle the condition.

**Comment by dagema1** [comment]
Yeah, my current implementation uses the Custom filter method. I asked this question because there is a similar usage in Automapper where you would pass the data while projecting.

you can see the [Parameterization](https://docs.automapper.org/en/latest/Queryable-Extensions.html#parameterization) part of the doc to make my question clear.

Thank You.

**Comment by hasanmanzak** [comment]
Yeah, I see your reasoning. But I will stick with my original argument. This is very solveable with custom filter methods. To handle this kind of expression parameterization would be a PITA as this is not only a value parameterization but with method calls also. I'm sorry, I would vote against this.

**Comment by minasploit** [comment]
> No, this is not possible with the way how `SievePropertyMapper` works. Even if it was, logically, this is bogus. Say the development is done to support that kind of mapping. Think about it, when runtime hits that `.Property<>` line, `userId` is converted to an expression constant, it won't be a dynamic value. Or look it this way, where would the `userId` value is supplied to execute the expression `s => s.UserId == userId` if your intention was to use a variable?
> 
> This is textbook [Custom Filter Method](https://github.com/Biarity/Sieve#add-custom-sortfilter-methods) implementation, which would handle the condition.

Let's say instead of a `userId`, the ID of the currently logged in user is used as `User.Identity.Name`.

This let's say works in providing a value, would this fail because of the `Property<>` line being converted to a constant expression? 

Follwing what a constant expression is...

> A constant-expression is an expression that can be fully evaluated at compile-time.

The `User.Identity.Name` field will fail at providing a value at compile-time right?

**Comment by hasanmanzak** [comment]
No. I might be misleading, sorry about that. `Property<>` line is not being converted to a constant expression[1, 2]. When `Property<T>` line runs, `p.Subscribers.Any(s => s.UserId == userId)` is treated as a member of T, but it's not. `.Any(s => s.UserId == userId)` or `User.Identity.Name` or `bla` discussion goes very deep into expressions, parameter capturing, clousures, value capturing, value swaps etc. [SievePropertyMapper](https://github.com/Biarity/Sieve/blob/master/Sieve/Services/SievePropertyMapper.cs) is not an expression configuration builder and does not support those kind of full control over expressions. It just [finds](https://github.com/Biarity/Sieve/blob/master/Sieve/Services/SievePropertyMapper.cs#L79) the designated property or field: member.

[1] To be clear, when I said "... expression constant ..." I mean `a constant value in the expression`. **A Constant Expression** and [Linq.Expressions.ConstantExpression](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.constantexpression?view=net-5.0) are not the same.

[2] The term `Constant Expression` is in language semantics domain:

    public void Test<T>(T val)
    {
        Type t = null; // a constant expression. compiler can evaluate this.
        t = typeof(T); // a constant expression. compiler can evaluate this.
        t = val.GetType(); // not a constant expression. compiler can not evaluate this. this has to be evaluated at run-time.
    }

**Comment by minasploit** [comment]
Ahhh, that makes sense. 

For now, the [Custom Filter](https://github.com/Biarity/Sieve#add-custom-sortfilter-methods) method will suffice. Thanks for the help.

**Comment by dagema1** [comment]
Thanks for helping @hasanmanzak
