### ISSUE TITLE
Non-parseable DateTime leads to FormatException 

### ISSUE THREAD

**Issue by tflanitzer** [Biarity/Sieve#11]
Actual behaviour: When filtering a DateTime field with "createdat > 2018", a FormatException is thrown ("FormatException: String was not recognized as a valid DateTime.")

Expected behaviour: Sieve should catch the FormatException and throw a sieve exception.

This may also happen with integers or other data types, although I haven't tested or checked.

**Comment by Biarity** [comment]
Done! Will be in 1.3.92.
