### ISSUE TITLE
AND operator uses wrong bitwise operator instead of AndAlso expression

### ISSUE THREAD

**Issue by TilmannBach** [Biarity/Sieve#115]
https://github.com/Biarity/Sieve/blob/803055029e61691108d9da32c65f4c0078615f0e/Sieve/Services/SieveProcessor.cs#L264

* Expression.And creates bitwise `&`
* Expression.AndAlso creates `AND` operator
* this should be `Expression.AndAlso` like the other occurences. Otherwise there is a wrong SQL in the consequence which results in bugs like this: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1289

**Comment by carlesUdG** [comment]
This issue may be duplicated: [https://github.com/Biarity/Sieve/issues/101](https://github.com/Biarity/Sieve/issues/101)

**Comment by TilmannBach** [comment]
hi @a-patel thanks for merging the linked MR in this issue, but can you do a nuget release as well?
or are there any special politics on releasing new versions to nuget?
