### ISSUE TITLE
Argument 1: cannot convert from '....' to 'Sieve.Models.ISieveModel<Sieve.Models.IFilterTerm, Sieve.Models.ISortTerm>'

### ISSUE THREAD

**Issue by mzgnr** [Biarity/Sieve#12]
I followed your readme and having this issue. What might cause that ?

```
var result = _context.TblObjectOutTemplateItem.AsNoTracking();
result = _sieveProcessor.ApplyAll(item, result); 
```

and my model is simple as your test models

**Comment by Biarity** [comment]
Do you mind showing the entire error? What's in "..."? Is `item` a `SieveModel`?

**Comment by bbartels** [comment]
Result is of a different type than what ApplyAll returns. Try this:
    result = _sieveProcessor.ApplyAll(item, _context.TblObjectOutTemplateItem.AsNoTracking());

**Comment by mzgnr** [comment]
Unable to resolve service for type 'Sieve.Services.ISieveProcessor' while attempting to activate 'XXXX.Controllers.ZZZZController

**Comment by mzgnr** [comment]
I fixed the previous error. I'm now having this one

**Comment by Biarity** [comment]
You're not injecting `ISieveProcessor` yet using it in `ZZZZController`.
