### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by gsandorx** [Biarity/Sieve#123]
I know the original author passed the chairman role to @a-patel , but the later hasn't been doing much. There are a few PRs that have been waiting for approval for months. 

Any idea what is going on? Thanks :)

**Comment by a-patel** [comment]
Sorry for the inconvenience. 
I am a bit busy these days, so I am not actively looking into this project.
I have reviewed the few PRs and merged them.

**Comment by ITDancer13** [comment]
I @a-patel we had the same issue that Sieve is a great project but not really well maintained at the moment. Unfortunately I didn't hear that you're the new maintainer and we started a fork of Sieve called Pagr https://github.com/ITDancer13/Pagr as I couldn't reach Biarity. If you like my changes and plans for further changes and improvements I'd be happy if we can get in touch to maintain Sieve together in future --> I would delete my fork again.

**Comment by Biarity** [comment]
Hi @ITDancer13! Unfortunately I'm swamped with commitments in my life so I don't expect to have any time for serious OSS development any time soon. 

I appreciate the time you put into the fork, and you have my blessing if it means anything! I'm definitely on the look out for an active maintainer/product "owner", and very happy to make you one for this project if you're up for it :)

**Comment by ITDancer13** [comment]
Hi Biarity,I'm very happy to heart that. Forking it was the last option so I'm happy that I can contribute to the original project. I hope to continue it as good as possible. Can you please help me to align the license file to get your copyright into it. I tried my best in my fork but unfortunately I was only able to mention you with your github name.I'll move my fixes (except renaming) in the next hours to a pull request. How do you want to proceed with the nuget packages. As github project and nuget project still belongs to you, I will not be able to manage anything there or push new versions. Best regards from Germany, Kevin Am 13.05.2021 09:26 schrieb Biarity ***@***.***>:
Hi @ITDancer13! Unfortunately I'm swamped with commitments in my life so I don't expect to have any time for serious OSS development any time soon.
I appreciate the time you put into the fork, and you have my blessing if it means anything! I'm definitely on the look out for an active maintainer/product "owner", and very happy to make you one for this project if you're up for it :)

**Comment by Biarity** [comment]
Good to hear, I've invited you as a collaborator. For nuget packages, I am happy to publish new releases on request as I have been doing with @a-patel. Another way is if you could set up some CD pipeline I'd be happy to add the api key in the actions secrets for automated publication and to track releases on GH.

**Comment by ITDancer13** [comment]
A CD pipeline with github releases sounds great to be able to release some preview etc as well. I'll prepare everything for it.

**Comment by hasanmanzak** [comment]
Hey, guys! I really am up for the maintenance of this project, also!

Joking aside, in the previous months, I had some free time to contribute the project, just a little bit. Since then, I was extremely busy and wasn't be able to dive deep with the issues. In the meantime, the workload I've been struggling with will be diminish very soon and I'll be returning :)

I really love the library and really would love it to grow bigger!.. So, if needed, count me in!

**Comment by ITDancer13** [comment]
@hasanmanzak great to hear that :-)

I started a pull request today with all changes that I made in my fork Pagr in the last few weeks: https://github.com/Biarity/Sieve/pull/126

Preparation for CI / CD and some bug fixes.

I would be happy to get some feedback from you guys if this is the right direction for Sieve before I close my fork ;-)

**Comment by gsandorx** [comment]
@ITDancer13  I worked on a set of changes that enabled Sieve to do filtering/sorting by default, without requiring explicit configuration via attributes (or using the fluent api). It also works for nested members and you can still indicate whether a particular member shouldn't be sorted/filtered

Would you be interested in merging this into Pagr?

**Comment by hasanmanzak** [comment]
> 
> 
> @hasanmanzak great to hear that :-)
> 
> I started a pull request today with all changes that I made in my fork Pagr in the last few weeks: #126
> 
> Preparation for CI / CD and some bug fixes.
> 
> I would be happy to get some feedback from you guys if this is the right direction for Sieve before I close my fork ;-)

Can you give reference to current issues here, if any relates to your fixes?

**Comment by ITDancer13** [comment]
@gsandorx that sounds interesting.

 Currently I'm writing for the original author @Biarity and @a-patel if they like to have my changes from Pagr in Sieve. If they accept it and I can setup a CD pipeline which allows me to release new versions on my own, I'll stop working on Pagr and maintain Sieve instead.

If they don't like it or want to do so, I'll continue my work on Pagr an I would be happy about contribution there :)

**Comment by Biarity** [comment]
@hasanmanzak Yes it would be great to have you on board, will invite you in as well!

@ITDancer13 Thanks, will review and merge shortly...

@gsandorx I'm happy to have that feature, however I think it should be made opt-in eg. via a configuration flag.

**Comment by Biarity** [comment]
Closing but feel free to open separate issues to disucss anything further
