### ISSUE TITLE
Branches are not protected

### ISSUE THREAD

**Issue by ITDancer13** [Biarity/Sieve#128]
@Biarity unfortunately I cannot setup branch policies which I need to setup a stable release process with pipelines. Can you please protect `master` and `releases/*`. It should only be possible to create PRs to those branches (and at least one contributors has to approve the PR anyway). 

I'd like to build releases like this: 

- master: All official releases are built from master branch. We can merge non-breaking bug fixes directly to master.
- releases/{version-number}: These branches are started as soon as there is a first breaking change coming up. All changes dependent on this have to be merged to the next major version. Pre-releases are built based on those branches. As soon as it's merged back to master, the new major version gets released.

I started the `release/3.0.0` branch and did the first pre-release to nuget --> Nuget Api Key in secrets works as expected :-)

**Comment by Biarity** [comment]
Good call, all done!
