### ISSUE TITLE
Issue templates, Labels, Projects & Milestones

### ISSUE THREAD

**Issue by hasanmanzak** [Biarity/Sieve#129]
I think we should prepare some templates to provide people to be able to communicate more smoothly.

Currently open issues are about
* either something is working but the use case is different and the author asks about that feature to work the other way,
* or something is not working and 
  * either it is actually not a feature of the library and if we put a work on then it would be a nice addition to the library,
  * or is a bug.

All of those are very hard to follow and seperate and manage and etc etc.

For example, I would like to discuss these issues with the maintainers:
#2 
#10 
#37 
#77 
#104 
#106 
#120 

Last but not least, not only we need the templates but we can also benefit from the projects board and milestones aswell. Issue lifetime management, PR management, Preview releases, targeted releases.. C'mon! :)

**Comment by ITDancer13** [comment]
I think that's a great idea. I'm setting up a pipeline based on GitHub Actions to be able to publish (pre-)releases automatically. As soon as this works, I'd like to screen all open issues. As I'm not familiar with the features of managing issues and projects in GitHub it would be great if you (or someone else) can assist me with that.

**Comment by ITDancer13** [comment]
@hasanmanzak according to the other issue, @Biarity invited you to maintain Sieve, too. Is that correct? If yes, I think we're a couple of maintainers now and we should sync on what to do next and what do we want to solve for the next release.

**Comment by Biarity** [comment]
I've added a basic issue template for bugs. For new feature requests and other discussion we'll use [the discussions tab](https://github.com/Biarity/Sieve/discussions). We can use upvotes there as a means of prioritization. 

We should close any issues that are feature requests and re-open them as discussions. My next priority is to close off as much stale PRs/issues as possible and ensure some stability so we can safely focus on new features. I want to have a v2.5 where we do that, then perhaps brainstorm some new ideas for v3. 

I see this project headed towards becoming a lightweight, more customizeable OData/GraphQL alternative, so next steps may include writing a more efficient parser, writing a JS client library, or adding select/search/etc. Any thoughts?
