### ISSUE TITLE
Unintended breaking change in 2.5.0-beta0003

### ISSUE THREAD

**Issue by ITDancer13** [Biarity/Sieve#135]
**Describe the bug**
`protected virtual SievePropertyMapper MapProperties(SievePropertyMapper mapper)` is not called in constructor anymore. We're overriding this method to get access to `SievePropertyMapper` (as it's internal at the moment). 

**To Reproduce**
1. Derive from `SieveProcessor`
2. Override `protected virtual SievePropertyMapper MapProperties(SievePropertyMapper mapper)` and store given `SievePropertyMapper mapper` in your derived class.
3. Try to access stored `SievePropertyMapper mapper` in constructor --> It's never set.

**Expected behavior**
Even if this is not intended to be used this way, this breaking change in should be reverted in version 2.5. For version 3.0 we should think about to change visibility of `SievePropertyMapper Mapper` to `protected`.

**Comment by hasanmanzak** [comment]
Let me fix this in a couple of hours. I'm not on the computer right now.

**Comment by hasanmanzak** [comment]
Now I'm on the computer :) Let's think about this again:

Virtual method calls in constructors are anti-patterns. There is a very good [Stackoverflow thread](https://stackoverflow.com/questions/119506/virtual-member-call-in-a-constructor) and a couple of very good articles ([part-1](https://docs.microsoft.com/en-us/archive/blogs/ericlippert/why-do-initializers-run-in-the-opposite-order-as-constructors-part-one), [part-2](https://docs.microsoft.com/en-us/archive/blogs/ericlippert/why-do-initializers-run-in-the-opposite-order-as-constructors-part-two)) about this.

I intend to avoid this anti-pattern. I'd rather not changing it back to call in constructor but the use case `Try to access stored SievePropertyMapper mapper **in constructor** ` changes everything.

Also, I think a method should not expose a private and readonly field out of the scope, `MapProperties` exposes.

I'm reverting the change, but this needs a unit test :) As for v3, I suggest not to change the visibility only but to change the way that builder acts.
