### ISSUE TITLE
Fluent API: support like EF IEntityTypeConfiguration for seperate domain entity

### ISSUE THREAD

**Issue by a-patel** [Biarity/Sieve#14]
I do not want to change the domain entities using a decorator.
I want something like this,

```
            //dynamically load all configuration
            //System.Type configType = typeof(LanguageMap);   //any of your configuration classes here

            var typesToRegister = Assembly.GetExecutingAssembly().GetTypes()
            .Where(type => !string.IsNullOrEmpty(type.Namespace))
            .Where(type => type.BaseType != null && type.BaseType.IsGenericType &&
                type.BaseType.GetGenericTypeDefinition() == typeof(EntityTypeConfiguration<>));
            foreach (var type in typesToRegister)
            {
                dynamic configurationInstance = Activator.CreateInstance(type);
                modelBuilder.ApplyConfiguration(configurationInstance);
            }
            //...or do it manually below. For example,
            //modelBuilder.Configurations.Add(new LanguageMap());
```

**Comment by a-patel** [comment]
FYI.
another approach,
https://github.com/tflanitzer/Sieve/blob/explicit-properties/SieveTests/Controllers/PostsController.cs

**Comment by Biarity** [comment]
Fluent API is already supported: https://github.com/Biarity/Sieve/issues/4#issuecomment-364629048

**Comment by a-patel** [comment]
I know Fluent API is supported already.
I want to load/register Fluent API for particular domain dynamically.
e.g. find base class or interface implementation in assemblies.

**Comment by a-patel** [comment]
I have also looked into the pull request,
https://github.com/tflanitzer/Sieve/tree/explicit-properties

I want similar that kind of approach, but not in controller.

**Comment by a-patel** [comment]
```
public partial class BlogPostMap : IEntityTypeConfiguration<BlogPost>
    {
        public override void Configure(EntityTypeBuilder<BlogPost> builder)
        {
            base.Configure(builder);
            builder.ToTable("BlogPost");
            builder.HasKey(bp => bp.Id);
            builder.Property(bp => bp.Title).IsRequired();
            builder.Property(bp => bp.Body).IsRequired();
            builder.Property(bp => bp.MetaKeywords).HasMaxLength(400);
            builder.Property(bp => bp.MetaTitle).HasMaxLength(400);
        }
    }
```

I am asking for such functionality.
So one can find the IEntityTypeConfiguration implementation in other assembly and load them dynamically.

**Comment by a-patel** [comment]
This is just suggestion,
#Good to Have feature.

**Comment by Biarity** [comment]
What if you create multiple subclasses with different fluent APIs then use something like DI to choose the one you want to be used?

**Comment by a-patel** [comment]
It will be great if you can give me an example code.
Thank you in advance.

**Comment by a-patel** [comment]
any update?

**Comment by Biarity** [comment]
Sorr for the delay - I meant creating multiple subclasses of `SieveProcessor` (instead of just the 1 as you'd do for the fluent API normally). Then you'd be able to manually choose which implementation to use.

**Comment by a-patel** [comment]
then how to register 'SieveProcessor'?
It will be very very helpful, if you can give an example.

**Comment by a-patel** [comment]
Basically I want new change in core functionality,
I need to find all classes which implemented one base class/interface (i.e. IEntityTypeConfiguration in EF API) in particular assembly(es),
and register such classes in SieveProcessor.

Hope you understand my requirement.

**Comment by a-patel** [comment]
please do the needful.
thank you

**Comment by Biarity** [comment]
Creating multiple subclasses looks like:
```C#
public class ApplicationSieveProcessorOne : SieveProcessor
{
    public ApplicationSieveProcessor(
        IOptions<SieveOptions> options, 
        ISieveCustomSortMethods customSortMethods, 
        ISieveCustomFilterMethods customFilterMethods) 
        : base(options, customSortMethods, customFilterMethods)
    {
    }

    protected override SievePropertyMapper MapProperties(SievePropertyMapper mapper)
    {
      //mapper details from issue #4
    }
}
```
and another one
```C#
public class ApplicationSieveProcessorTwo : SieveProcessor
{
    public ApplicationSieveProcessor(
        IOptions<SieveOptions> options, 
        ISieveCustomSortMethods customSortMethods, 
        ISieveCustomFilterMethods customFilterMethods) 
        : base(options, customSortMethods, customFilterMethods)
    {
    }

    protected override SievePropertyMapper MapProperties(SievePropertyMapper mapper)
    {
      //DIFFERENT mapper details from issue #4
    }
}
```
Now just use whichever class you want. I'm not really sure why this wouldn't work for ya. Are you using it with ASP.NET Core and the default DI? If so, you can easily inject whichever class you want in Startup.cs.

**Comment by Dzivo** [comment]
I dont aggree with you @Biarity this is very inefective. 

EF Core enables us to use builder from our models without any other setup you just need to implement interface. This should be that hard to implement since you already have SieveProcessor.

If you would like i can make a pull request but only if you are interested in such a feature :)

**Comment by Dzivo** [comment]
For now i use something like this

```
public class MyEntity : ISieveConfiguration
{
  public string Name { get; set; }

  public void ConfigureSieve(SievePropertyMapper mapper)
  {
    mapper.Property<Regatta>(p => p.Name)
      .CanFilter();
  }
}

public interface ISieveConfiguration
{
  public void ConfigureSieve(SievePropertyMapper mapper);
}

public class CustomSieveProcessor : SieveProcessor
{
    public CustomSieveProcessor(
        IOptions<SieveOptions> options)
        : base(options)
    {
    }

    protected override SievePropertyMapper MapProperties(SievePropertyMapper mapper)
    {
      Assembly
        .GetExecutingAssembly()
        .GetTypes()
        .Where(m => m.GetInterfaces().Any(i => i == typeof(ISieveProcessor)))
        .ToList()
        .ForEach(m =>
        {
          var instance = Activator.CreateInstance(m);
          m.GetMethod("ConfigureSieve").Invoke(m, new object[] { mapper });
        });

      return mapper;
    }
}
```
