### ISSUE TITLE
Target Framework

### ISSUE THREAD

**Issue by thj-dk** [Biarity/Sieve#16]
Thanks for sharing this project 👍 

Why do you target .NET Core 2 and not .NET Standard 2? I'd like to use this for ASP.NET Core project that targets .NET Framework 4.7.

**Comment by OneFishTwoFishRedFish-JFish** [comment]
Came here to suggest this. The only code that needs to be replaced/changed is the TryAdd in the SievePropertyManager. Other than that I only had to add a couple nuget packages.

**Comment by Biarity** [comment]
Will look into this later today

**Comment by Biarity** [comment]
All done!

**Comment by thj-dk** [comment]
Much appreciated!
