### ISSUE TITLE
The offset specified in a OFFSET clause may not be negative.

### ISSUE THREAD

**Issue by muhammetsahin** [Biarity/Sieve#17]
Hi there,

I'm using UnitOfWork and wrote this method but I'm getting this error:

`The offset specified in a OFFSET clause may not be negative.`

```  
public IQueryable<Note> GetAll(SieveModel sieveModel)
    {
      var result = UnitOfWork.Select<Note>()
                             .Where(s => (s is Note) && s.IsDeleted == false && s.NoteType == "Note" && s.UserUid == _currentUser.Uid)
                             .AsNoTracking();

      result = _sieveProcessor.ApplyAll(sieveModel, result);
      return result;
    } 
```

Is this a bug?

Thanks.

**Comment by Biarity** [comment]
What version are you using? What line is the error?

**Comment by muhammetsahin** [comment]
I'm using latest version (1.3.94) and error line is 

 _sieveProcessor.ApplyAll(sieveModel, result);

Thanks.

**Comment by Biarity** [comment]
Can you provide more details on the error (eg. call stack)? Also can you try version 1.3.93 and see if this issue persists?

**Comment by muhammetsahin** [comment]
I found problem. It was my fault.

Page request parameter should start 1 not 0.

You  already wrote in the document but missed it

GET /GetPosts

?sorts=     LikeCount,CommentCount,-created         // sort by likes, then comments, then descendingly by date created 
&filters=   LikeCount>10, Title@=awesome title,     // filter to posts with more than 10 likes, and a title that contains the phrase "awesome title"
&page=      1                                       // get the first page...
&pageSize=  10                                      // ...which contains 10 posts
