### ISSUE TITLE
problem when filtering by DateTime (Npgsql.Entity Framework Core.PostgreSQL v6)

### ISSUE THREAD

**Issue by hummer007** [Biarity/Sieve#172]
**Describe the bug**
There is a problem when filtering by DateTime if i use Npgsql.Entity Framework Core.PostgreSQL v6+

**To Reproduce**
Try to filter by DateTime field.
Url example "https://localhost:5001/api/products?filters=createdAtUtc>=2022-02-24T11:58:01.481Z"

**Expected behavior**
Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/13252220/155516564-18bacf64-a812-4d18-bc6d-a3c6ce2caca6.png)
![Screenshot_1](https://user-images.githubusercontent.com/13252220/155519962-a5a18c9e-437d-411d-b1af-732d5f087582.png)

**Comment by hasanmanzak** [comment]
It's a mapping problem not a Sieve problem actually, when using PostgreSQL. Here's a breif explanation:

    public class SomeEntity
    {
        public long Id { get; protected set; }
        public DateTime CreatedAtUtc { get; protected set; }
    }
    
When ORM instantiates this class `CreatedAtUtc` property is a `DateTime` value with `Kind` property set to `DateTimeKind.Unspecified`. You have to tell your mapping that you are mapping a UTC field or so. If not, ORM auto mapping will map to a `DateTimeType`.

For example, NHibernate has `AbstractDateTimeType` class and classes inherits from this. `UtcDateTimeType` is one of them and within my domain logic, all datetime values are UTC values. Thus, I have property mapping convention to treat all `DateTime` properties to map to `UtcDateTimeType`:

    using System;
    using FluentNHibernate.Conventions;
    using FluentNHibernate.Conventions.Instances;
    using System.Reflection;
    using NHibernate.Type;

    internal class NhPropertyConvention: IPropertyConvention
    {
        public void Apply(IPropertyInstance instance)
        {
            var memberInfo = instance.Property.MemberInfo;

            // some other logic
            
            // force all DateTime data to be UTC
            if (memberInfo is PropertyInfo propertyInfo && propertyInfo.PropertyType.IsAssignableFrom(typeof(DateTime)))
                instance.CustomType<UtcDateTimeType>();
        }
    }
    
But why two different errors, with `DateTimeKind.Unspecified` and `DateTimeKind.Local`? Here's why..

When you send `2022-02-24T11:58:01.481Z`, Sieve knows, actually `System.DateTime` knows what `DateTimeKind` it holds: `DateTime with Time Zone` which yields to `UTC`. But the entity read from DB has `DateTimeKind.Unspecified`.

When you send `2022-02-24T11:58:01.481`, Sieve knows, actually again, `System.DateTime` knows what `DateTimeKind` it holds: `DateTime with No Time Zone` which yields to `Local`. But the entity read from DB has `DateTimeKind.Unspecified`.
