### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by maskalek** [Biarity/Sieve#186]
Is this project dead? Any alternatives/forks?

**Comment by ITDancer13** [comment]
Unfortunately I was not able to jump into the project as I wanted. But I still want to keep it running if some others are still with me. I try to release version 3 a soon as possible.

**Comment by hasanmanzak** [comment]
No actually. I'm also like @ITDancer13, could not be able to find the time and put the work down.. I'm gonna to be more active within the project in the upcoming future!
