### ISSUE TITLE
OR conditions are implemented as AND 

### ISSUE THREAD

**Issue by fruel** [Biarity/Sieve#19]
(I think this is the issue @davidnmbond mentioned in #8 )

In [SieveModel.cs](https://github.com/Biarity/Sieve/blob/afbd41e0908316885a1c9192d47ab4bc8ed44c25/Sieve/Models/SieveModel.cs#L32-L37) where the filter expression is parsed only more AND-conditions are added to the list of filter items. 

I think the issue happened because of a typo in the unit test [here](https://github.com/Biarity/Sieve/blob/c861ada8fa274eaf9c38e345029be414fdad54bb/SieveUnitTests/General.cs#L46). I assume the value for `Title` should be `"D"` not `"3"` - then the test fails as expected.

**Comment by Biarity** [comment]
Yup, just realised this doesn't actually do any OR logic. I'll be rewriting the parser in a proper framework ASAP. Sorry about that!

**Comment by davidnmbond** [comment]
Confirmed - the unit test is wrong - changing the term was stated means that unit tests (correctly) fail.
Looking into a fix now...

**Comment by Biarity** [comment]
Published to nuget as 2.1.0. Thanks for your efforts!

**Comment by davidnmbond** [comment]
No problem - I'm looking forward to seeing/helping Sieve develop further.  If you need a hand, please add me as a contributor.

**Comment by Biarity** [comment]
That would be great! Looking at open issues - I was going to rewrite the parser next in something like [Sparche](https://github.com/sprache/Sprache) to add flexibility and allow escape sequences, arbitrary logic, & data shaping. Of course that necessitates a more flexible way of converting the query to LINQ, meaning part of `SieveProcessor.ApplyFiltering` would also need to be rewritten.

**Comment by AlexandreBonfim** [comment]
> Yup, just realised this doesn't actually do any OR logic. I'll be rewriting the parser in a proper framework ASAP. Sorry about that!

@Biarity How can I use OR logic? For example filters=Name@=*test,location@=*malta ...

Thanks, your library save a lot of time! :)

**Comment by Biarity** [comment]
I'll be working on this later but unfortunately am quite buys at the moment.
