### ISSUE TITLE
Child resources

### ISSUE THREAD

**Issue by seddie62** [Biarity/Sieve#27]
I tried implementing sorting and pagination on child resources and couldn't successfully execute it. I was wondering if I missed something or child resources are not accounted for currently

**Comment by Biarity** [comment]
Can you elaborate on what you mean by "child resources"? Not familiar with that term.

**Comment by seddie62** [comment]
Let me give an example

public class Author{
     public string Name {get;set;}
     public Book Book {get;set;}
}

public class Book{
    public string Title {get;set;}
    public DateTime Year {get;set;}
}

So supposing I want to get all the books of a particular author filtered,
how do I do that?

**Comment by Biarity** [comment]
This is not currently supported - see #10. Sieve would try to cast a `string` (your query) to `Book`, which will fail. 

Only thing you could do is to make [a custom filter](https://github.com/Biarity/Sieve#add-custom-sortfilter-methods) that would explicitly do exactly what you want while allowing for more flexibility.
