### ISSUE TITLE
Custom Filters need to be before standard Filters?

### ISSUE THREAD

**Issue by zolrath** [Biarity/Sieve#28]
Hi!

I have an implementation of ISieveCustomFilterMethods for a custom search filter named `contains`.

If I use the query string `?filters=contains@=robots,categoryId==12` the results are properly filtered with the search and the category.

If I switch the order of the standard filter and the custom filter: `?filters=categoryId==12,contains@=robots` Sieve fails to filter and I get all of the results instead.

**Comment by Biarity** [comment]
That's weird, the comma in your query should've applied an AND so the order shouldn't matter. Does this happen regardless of what code you've got in `contains`? 

Also if you're using v>=2.0.0, can you see if this persists with v<=1.3.94 (or vice versa)?

**Comment by Biarity** [comment]
Never mind, spotted the bug!

**Comment by Biarity** [comment]
Fixed in [v2.1.2](https://www.nuget.org/packages/Sieve/2.1.2).
