### ISSUE TITLE
Add sample projects

### ISSUE THREAD

**Issue by Deilan** [Biarity/Sieve#35]
Please add sample projects with examples of end-to-end usage in ASP.NET Core 2.1 with:
1. [Entity Framework Core 2.1](https://github.com/aspnet/EntityFrameworkCore/tree/release/2.1)
2. [MongoDB C# Driver](https://github.com/mongodb/mongo-csharp-driver)

**Comment by Biarity** [comment]
There's already an EF Core sample project ([here](https://github.com/Biarity/Sieve/tree/master/SieveTests), apologies for the unfortunate name). I don't plan on making a sample project for other ORMs/data frameworks. The `SieveProcessor.Apply` method accepts and returns an [`IQueryable`](https://github.com/Biarity/Sieve/blob/f74eb2f7df7ab83942f2b62348049739dd6eac19/Sieve/Services/SieveProcessor.cs#L109),  so it should be quite trivial to set it up with other frameworks regardless of the project's structure.
