### ISSUE TITLE
OR logic for same property

### ISSUE THREAD

**Issue by mfahadi** [Biarity/Sieve#41]
I have been using Sieve for quite some time now and it works great. I was wondering if it is possible to do or logic on same property with different values.

i.e. Book { Title, Author }

Is there a way to filter on books with title "Gulliver's Travels" OR "The Society of Mind"],

Thank you

**Comment by chriseyhorn** [comment]
I'm also wondering how to get this working.  For example I need to be able to have a filter with multiple OR values.

LocationName==Foo OR Bar

Is there a way to achieve this in one query?

**Comment by Sigvaard** [comment]
I have the same issue. There should be some OR for values too.

**Comment by chriseyhorn** [comment]
@Biarity Any chance you could point us in a direction for this one?

**Comment by Biarity** [comment]
You can now use pipes in value fields to for OR logic.
