### ISSUE TITLE
Sieve without EF

### ISSUE THREAD

**Issue by rdagumampan** [Biarity/Sieve#42]
Hi guys, 

Was wondering if its possible to achieve this without dependency to EF? Would it be possible to just derive the SQL from the filters and annotated models? Then I can use plain SqlConnection and DataReaders for getting the object from any SQL92 source.

Appreciate your feedback.

Br, Rodel

**Comment by Biarity** [comment]
Sieve only has a dependency on LINQ, not EF as far as I'm aware. So it should work if you can get SQL from an IQueryable right?

**Comment by frode** [comment]
Correct @Biarity, Sieve works fine without EF.. You can close this issue.
