### ISSUE TITLE
SQL exception conversion failed when converting date and/or time from character string

### ISSUE THREAD

**Issue by Shangshin-Liu** [Biarity/Sieve#44]
Hi,

I enjoy the package a lot. But I have a problem, I hope to find answer to solve it. Please help me! 

When I query with datetime data format, I'll get exception with ```sql exception conversion failed when converting date and/or time from character string```.

This is the SieveModel(with ```Newtonsoft.Json.JsonConvert``` to get object string):
```
{"Filters":"datetimeColumn>2018-10-10","Sorts":null,"Page":null,"PageSize":null}
```
I use SQL Server Prefilter to check the sql, and I found that will be transfer to:
```sql
exec sp_executesql N'SELECT [p].[ID], [p].[datetimeColumn]
FROM XXX_table AS [p]
WHERE ([p].[datetimeColumn] > ''2018-10-10T00:00:00'')
ORDER BY (SELECT 1)
OFFSET @__p_0 ROWS',N'@__p_0 int',@__p_0=0
```
In above sql, I found the ```where``` statement  will add twice 「'」char. Dose there anyone have the same problem?

Thanks!

PS.  My develop environment
```
Microsoft.AspNetCore.App 2.1.5 
Sieve 2.1.5
```

**Comment by Shangshin-Liu** [comment]
Oh, I found the problem!! 
It is not char problem but sql ```datetime type```(not ```datetime2```) not supported issue.
Can you support to this sql data type ```datetime```?

error: ```2018-10-10T00:00:00.0000000``` 
success:  ```2018-10-10T00:00:00.000```

**Comment by Biarity** [comment]
So Sieve doesn't directly deal with date types. [This line](https://github.com/Biarity/Sieve/blob/2d5fc0d2329a1d9d72b80b990e2ca655070be549/Sieve/Services/SieveProcessor.cs#L188) is all the type conversion code there is, and I was thinking I won't make any special cases and instead just use these functions out of the box.

**Comment by Shangshin-Liu** [comment]
Thank for replying. I decide to change datetime to datetime2.

**Comment by fivage** [comment]
It's an EF Core issue. 
EF will add microseconds to the SQL Parameter and this is not allowed by SQL Server. You can resolve this by specifying the Dbtype on the .NET property in the EntityTypeBuilder
   builder.Property(o => o.MyTimeStamp)
                .HasColumnType("DateTime");
