### ISSUE TITLE
Question: Getting Unsupported Media Type

### ISSUE THREAD

**Issue by JorgeValladares** [Biarity/Sieve#55]
Hi, 

I'm using net core 2.2. I have created a method but when I access the end point I keep getting the same error, it works with methods that doesn't use Sieve. I commented part of the code but still the same:
(Controller)
```
 public IActionResult GetProperties(SieveModel sieveModel)
        {
            string g = "a";
            /*
            try
            {
                var result = _repository.Property.GetFilteredProperties();
                result = _sieveProcessor.Apply(sieveModel, result);

                if(result == null)
                {
                    return NotFound();
                }
                else
                {
                    return Ok(result.ToList());
                }
            }
            catch (Exception ex)
            {*/
                return StatusCode(500, "Internal server error");
            //}  
        }
```
This is the implementation method GetFilteredProperties

```
        public IQueryable<Property> GetFilteredProperties()
        {
            return RepositoryContext.Properties.AsNoTracking();
        }
```
The exact error is: 
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.13","title":"Unsupported Media Type","status":415,"traceId":"0HLKG5K5FVU29:00000001"}

Any ideas?

**Comment by kieranhoney** [comment]
Hi Jorge,

If you are using the 2.2 API template from dotnet new add the [FromQuery] attribute infront of the model parameter, so change it from:

`public IActionResult GetProperties(SieveModel sieveModel)`

To:

`public IActionResult GetProperties([FromQuery] SieveModel sieveModel)`

It should then correctly pick it up. Currently it's trying to pull it from the body that's why you're getting the Unsupported Media Type error.

Best Regards,

Kieran

**Comment by JorgeValladares** [comment]
Hi @kieranhoney 

You are totally right. It works now. Thank you!!

**Comment by kieranhoney** [comment]
No problem at all, glad I could help.

**Comment by Biarity** [comment]
Thanks for helping @kieranhoney!

**Comment by Mrajpatel** [comment]
@kieranhoney Thanks for helping!!! A small problem was crashing my whole project

**Comment by codengine** [comment]
I just stumbled upon the same issue and was wondering if it makes sense to update the example in the README?
