### ISSUE TITLE
Support sort and filter on JsonProperty PropertyName

### ISSUE THREAD

**Issue by frode** [Biarity/Sieve#56]
When you have classes like the example below and want to filter/sort on the column names "updated_at" and "created_at" it doesn't work.

I use this GET request as an example:

Works:
`GET base_url/api/v1/assets?sorts=UpdatedAt`

Does not work:
`GET base_url/api/v1/assets?sorts=updated_at`

updated_at is the property that is exposed in the json body, so it makes more sense for an end-user to utilise this name.

``` C#
    public class Asset
    {
        [JsonIgnore]
        public int Id { get; set; }

        [Sieve(CanFilter = true, CanSort = true)]
        [JsonProperty(PropertyName = "created_at")]
        public DateTime CreatedAt { get; set; }

        [Sieve(CanFilter = true, CanSort = true)]
        [JsonProperty(PropertyName = "updated_at")]
        public DateTime UpdatedAt { get; set; }

    }
```

**Comment by yehia2amer** [comment]
Hi frode,

You can do something like that: `[Sieve(CanFilter = true, CanSort = true, Name = "updated_at")]`

Also if it is only about "Case Sensitivity" you can change that in configurations (appsettings.json) using
```
"Sieve": {
        "CaseSensitive":false,
    }
```
You can find here the docs for how to configure Sieve: https://github.com/Biarity/Sieve#configure-sieve

**Comment by frode** [comment]
Hi @yehia2amer,

Thank you, that solved my issues with using the exposed snake_cased field names by using the Name attribute.

**Comment by Biarity** [comment]
Thanks for helping @yehia2amer
