### ISSUE TITLE
A filter with multiple Names i.e. (field1|field2) will strip out parentheses from the value

### ISSUE THREAD

**Issue by seanmarthur** [Biarity/Sieve#69]
For example, the query `(fileName|path)@=test(2).docx`, after Sieve processes `GetFiltersParsed()`, the value becomes `test2.docx`, and thus the query is not returning valid results.

The query `fileName@=test(2).docx` does not strip the parentheses.

I tried escaping the parens in the query like `test\\(2\\).docx`, but that didn't work.

**Comment by emech-en** [comment]
@seanmarthur: I think you should escape with one backSlash `test\(2\).docx`

**Comment by seanmarthur** [comment]
Thanks for the reply - that is what I already tried (you have to escape the backslash - `\(` is not a valid character - `\\(` represents the string `\(`.)
![image](https://user-images.githubusercontent.com/11314077/63056051-3d668e00-beb5-11e9-965e-ff140d7e9463.png)

It doesn't work with that escape sequence.

**Comment by seanmarthur** [comment]
I believe I figured this out - I don't think it was the parens (although I have found that even escaped parens at the end of a query like `field==test)` will bomb no matter what...) - it turns out it was the spaces! 

This should be closed - there shouldn't be any issue with parens in text queries.
