### ISSUE TITLE
Invalid filter expressions are simply ignored

### ISSUE THREAD

**Issue by tflanitzer** [Biarity/Sieve#7]
When an invalid filter expression or a filter for a non-filterable property is passed to the SieveProcessor, it is simply ignored. With this behavior, it is not possible to give helpful feedback to consumers of an API, e.g. "400 - Invalid filters specified" or even "Filtering for 'description' is not allowed".

What would you think about throwing SieveExceptions in such cases?

**Comment by Biarity** [comment]
Yup, additionally there should be another exception for when the name of a custom filter/sort method is used with a different entity type. Working on it!

**Comment by Biarity** [comment]
I don't think it should be possible to tell the user if filtering/sorting something is "allowed" as in your example. This would allow a malicious user to map out your entity models. Instead in b625d15, an exception would be thrown once Sieve has failed to find a property or a custom method with that name - regardless of weather or not they exist internally. Let me know if you think there's a use case this implementation doesn't account for.

**Comment by Biarity** [comment]
Just finalized the implementation - made it so throwing exceptions is optional (e83f6479450f10940916df0cbd4ca1fa4440e463) and turned off by default. If you want Sieve to throw exceptions then set `ThrowExceptions` in configuration to `true`. Documented [here](https://github.com/Biarity/Sieve#handle-sieves-exceptions). IMO this will make it easier to get started with Sieve without having to write boilerplate exception handling code if you want to.

**Comment by tflanitzer** [comment]
Ok, works for me thank you.

**Comment by tflanitzer** [comment]
There is one thing though: Could you make a common base exception for sieve? This should go without much effort and allow easier exception handling (e.g. treat all sieve exceptions in one catch).

**Comment by Biarity** [comment]
Added a base type, see 67606e281ba732468ee8b0540bd82528747abaac.
