### ISSUE TITLE
What about .net core 3.0 ?

### ISSUE THREAD

**Issue by zamap** [Biarity/Sieve#72]

**Comment by mjuen** [comment]
The library is written in .NET Standard 2.0, which runs just fine on .NET Core 3.0.

**Comment by zamap** [comment]
try to check with last ef and C# 8.0 fluent filters @mjuen

**Comment by mjuen** [comment]
OK, now we're getting somewhere. So that actual issue is that the fluent API extension of Sieve isn't working with EntityFrameworkCore 3.0? 

If yes, could you adjust the issue accordingly and add some more information? 

> What about .net core 3.0

Isn't very descriptive and it's hard to identify the problem just on that.

**Comment by Dzivo** [comment]
Ok so when do you think this could work ?

**Comment by tkunstek** [comment]
I don't believe this is an issue and recommend closing it. Using the follow packages for a netcoreapp3.1:

`  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0" />
    <PackageReference Include="MSBuildGitHash" Version="0.5.1" />
    <PackageReference Include="Sieve" Version="2.3.3" />
  </ItemGroup>`

and an API call such as

`
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ScoringReferenceValue>>> GetScoringReferenceValues([FromQuery]SieveModel sieveModel)
        {
            var result = _context.ScoringReferenceValues.AsQueryable();
            result = _sieveProcessor.Apply(sieveModel, result);
            return await result.ToListAsync();

        }
`

everything works as expected.

**Comment by stefankip** [comment]
Works fine for me as well.

**Comment by ITDancer13** [comment]
Seems to be closed. Sample project is updated to netcore3.1, too.
