### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by Biarity** [Biarity/Sieve#73]
I'm not going to be available for the next few months. If you've already contributed to the project in some way and are interested in maintaining or improving this project please let me know.

**Comment by pietiepb** [comment]
@janverley you had some spare time?

**Comment by Immortalin** [comment]
Btw what happened to cierge?

**Comment by a-patel** [comment]
I have some spare time

**Comment by Biarity** [comment]
@a-patel I've invited you on as a collaborator :).
@Immortalin Cierge has various severe security vulnerabilities by now since it has not had an update in a year. There are serveral forks are out there now however.

**Comment by a-patel** [comment]
Thanks @Biarity

**Comment by skolmer** [comment]
Hey @a-patel, good news that you are willing to spend some time to support this project and help @Biarity. If you find some free time, we could discuss my pull request from march (https://github.com/Biarity/Sieve/pull/60) and those other pull requests that are now open for some time. Would be really great to see these features in a new nuget release. Thanks in advance.
