### ISSUE TITLE
Invalid handling of escaped characters

### ISSUE THREAD

**Issue by andreizhvaleuski** [Biarity/Sieve#80]
You can use backslashes to escape commas and pipes within value fields but backslash doesn't removed before applying queries.

**Comment by andreizhvaleuski** [comment]
![image](https://user-images.githubusercontent.com/30213401/71505796-9eed2f00-288f-11ea-9fe2-4c3759eb61a8.png)

**Comment by andreizhvaleuski** [comment]
SQL Server Profiler shows following query (part of the query):
`... WHERE CHARINDEX(N''one\, two'', [e].[FirstName]) > 0 ...`

**Comment by jonathanantoine** [comment]
Hello,

I use this custom SieveModel as a workaround : 
```
public class MySieveModel : SieveModel, ISieveModel<FilterTerm, SortTerm>
{
  public new List<FilterTerm> GetFiltersParsed()
  {
    return base.GetFiltersParsed()
      .Select(
        ft =>
        {
          if (ft.Values?.Any() == true)
          {
            for (var index = 0; index < ft.Values.Length; index++)
            {
              var filterValue = ft.Values[index];
              if (filterValue.IndexOf("\\,", StringComparison.InvariantCulture) >= 0)
              {
                ft.Values[index] = filterValue.Replace("\\,", ",");
              }
            }
          }
          return ft;
        }).ToList();
  }
}
```

**Comment by PatryxCShark** [comment]
Are you going to fix the problem and issue the corrected version of Sievie?
As I see the post is one year old and it wasn't correct in last version unfortunately.
